---
# tasks file for ansible-role-firewall

- name: Include OS-specific variables.
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'

- name: Define firewall_package.
  set_fact:
    firewall_package: '{{ __firewall_package }}'
    when: firewall_package is not defined

- name: Include OS-specific tasks.
  include_tasks: '{{ var_item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  loop_control:
    loop_var: var_item

- name: Ensure firewall service is running and enabled to start on boot.
  service:
    name: '{{ firewall_package }}'
    state: started
    enabled: yes
