---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Include OS-specific variables.
      include_vars: "{{ item }}"
      with_first_found:
        - 'vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - 'vars/{{ ansible_distribution }}.yml'
        - 'vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
        - 'vars/{{ ansible_os_family }}.yml'

    - name: Update apt cache.
      package:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include ansible-role-configure_firewall"
      include_role:
        name: "ansible-role-configure_firewall"
