---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Include variables.
      include_vars: 'vars/main.yml'

    - name: Update apt cache.
      package:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include ansible-role-configure_firewall"
      include_role:
        name: "ansible-role-configure_firewall"
